### ISSUE TITLE
Missing https://github.com/SAP-samples/datahub-integration-examples/blob/master/AppIntegrationExample/sac

### ISSUE THREAD

**Issue by Sygyzmundovych** [SAP-samples/datahub-integration-examples#13]
The scenario https://github.com/SAP-samples/datahub-integration-examples/blob/master/AppIntegrationExample/doc/HowToAnalyse.md seems incomplete.
And the link https://github.com/SAP-samples/datahub-integration-examples/blob/master/AppIntegrationExample/sac on the page is broken: there is no such destination.
Regards.

**Comment by KaiRoesner** [comment]
Thanks Vitaliy for pointing this out. I have fixed the broken link with #14 but will need to invlove another colleague to check the content.

**Comment by KaiRoesner** [comment]
Hi @Sygyzmundovych , can you please review the PR #14 ?
