### ISSUE TITLE
Missing image pull secrets for vscode app template

### ISSUE THREAD

**Issue by Phil0110** [SAP-samples/datahub-integration-examples#21]
Please add the following lines in GitWorkflow/vscode-app/content/vsystem/apps/vsc-app.json
Below 
```
            "deployment": {
                "spec": {
                    "template": {
                        "spec": {
```
insert
```
                            "imagePullSecrets": [
                                {
                                    "name": "{{ .vsystem.imagePullSecret }}"
                                }
                            ],
```
I do not have the permissions to push or create a PR

**Comment by KaiRoesner** [comment]
@csengstock , you want to have a look at this?

**Comment by csengstock** [comment]
@KaiRoesner : Added this pull request: https://github.com/SAP-samples/datahub-integration-examples/pull/22
Can you please review/merge it?

**Comment by csengstock** [comment]
Change has been merged.

**Comment by KaiRoesner** [comment]
Fix merged -> closing this ticket.
